FROM node:18-alpine
WORKDIR /app
COPY ../backend/package.json ../backend/package-lock.json* ./
RUN npm install --production=false
COPY ../backend ./
RUN npm run build
EXPOSE 5000
CMD ["node", "dist/main.js"]