FROM python:3.10-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg && rm -rf /var/lib/apt/lists/*
COPY ../ai/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ../ai ./
EXPOSE 5001
CMD ["python", "server.py"]
